### ISSUE TITLE
DownloadModels fails due to ShardClient error

### ISSUE THREAD

**Issue by bioprojects** [d-mcgrath/MetaPathPredict#5]
I'm trying to install MetaPathPredict, and at the last stage of installation, DownloadModels causes the following errors.

$ DownloadModels
Downloading MetaPathPredict models...
Traceback (most recent call last):
  File "/home/k-yahara/miniconda3/envs/MetaPathPredict/bin/DownloadModels", line 8, in <module>
    sys.exit(Download.download_models())
  File "/home/k-yahara/miniconda3/envs/MetaPathPredict/lib/python3.10/site-packages/metapathpredict/download_models.py", line 26, in download_models
    fs.get(model_0_dl_path, str(model_0_install_path))
  File "/home/k-yahara/miniconda3/envs/MetaPathPredict/lib/python3.10/site-packages/fsspec/spec.py", line 983, in get
    self.get_file(rpath, lpath, **kwargs)
  File "/home/k-yahara/miniconda3/envs/MetaPathPredict/lib/python3.10/site-packages/fsspec/spec.py", line 906, in get_file
    with self.open(rpath, "rb", **kwargs) as f1:
  File "/home/k-yahara/miniconda3/envs/MetaPathPredict/lib/python3.10/site-packages/fsspec/spec.py", line 1309, in open
    f = self._open(
  File "/home/k-yahara/miniconda3/envs/MetaPathPredict/lib/python3.10/site-packages/pyxet/file_system.py", line 457, in _open
    repo_handle = _manager.get_repo(url_path.remote)
RuntimeError: ShardClient Error: Client connection error: transport error

Could you please let me know how to fix this error and download the models?

Best wishes,

Koji Yahara

**Comment by d-mcgrath** [comment]
Hi Koji, thank you for sending me the stack traceback of the error you're encountering. Could you please tell me what OS your machine is running and if you have root access?

Best,
David

**Comment by traviswheeler** [comment]
Quick note for closure: the problem turned out to be some limitation on the server that Koji was using - it was unable to access the xet servers for some unknown reason. Switching to another system resolved the problem
